services:
  epusdt:
    image: gmwallet/epusdt:local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/epusdt.env:/app/.env:ro
      - epusdt-data:/app/data
    ports:
      - "50506:8000"

volumes:
  epusdt-data:
